### ISSUE TITLE
win10 build error

### ISSUE THREAD

**Issue by MayMrZ** [mcorino/wxRuby3#302] opened 2024-09-11 08:57 UTC
C:\Users\Administrator>gem install wxruby3
Fetching wxruby3-1.2.0.gem
Fetching nokogiri-1.16.7-x64-mingw-ucrt.gem
Fetching plat4m-1.1.0.gem
Successfully installed plat4m-1.1.0
Successfully installed nokogiri-1.16.7-x64-mingw-ucrt
Building native extensions. This could take a while...
ERROR:  Error installing wxruby3:
        ERROR: Failed to build gem native extension.

    current directory: D:/apps/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wxruby3-1.2.0/ext
D:/apps/Ruby31-x64/bin/ruby.exe mkrf_conf_ext.rb

current directory: D:/apps/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wxruby3-1.2.0/ext
D:/apps/Ruby31-x64/bin/ruby.exe -ID:/apps/Ruby31-x64/lib/ruby/3.1.0 -rrubygems D:/apps/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=D:/apps/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/wxruby3-1.2.0 RUBYLIBDIR\=D:/apps/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/wxruby3-1.2.0
(in D:/apps/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wxruby3-1.2.0)
ERROR: Unsupported Ruby platform!

rake failed, exit code 1

Gem files will remain installed in D:/apps/Ruby31-x64/lib/ruby/gems/3.1.0/gems/wxruby3-1.2.0 for inspection.
Results logged to D:/apps/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/wxruby3-1.2.0/gem_make.out

how to fix?

**Comment by mcorino** [comment] 2024-09-11 10:47
What version of Ruby are you running?
As documented on Windows only Ruby interpreters installed with the RubyInstaller packages are supported.
What is the value of the `RUBY_PLATFORM` constant of your Ruby? 
```
$ ruby -e "p RUBY_PLATFORM"
```

**Comment by MayMrZ** [comment] 2024-09-13 08:29
> What version of Ruby are you running? As documented on Windows only Ruby interpreters installed with the RubyInstaller packages are supported. What is the value of the `RUBY_PLATFORM` constant of your Ruby?
> 
> ```
> $ ruby -e "p RUBY_PLATFORM"
> ```


C:\Users\Administrator>ruby -e "p RUBY_PLATFORM"
"x64-mingw-ucrt"

unsupported ?

**Comment by mcorino** [comment] 2024-09-13 16:47
That version should work I think.
wxRuby3 is routinely tested with RubyInstaller 2.7 and the latest release (3.3 currently) without any problems.
I have no idea what is going wrong on your system.
When I have time I will add a run with your version to see if something pops up.

**Comment by MayMrZ** [comment] 2024-09-14 01:18
thaks

**Comment by mcorino** [comment] 2024-09-14 06:54
Sorry, I cannot reproduce your problem. The Github Actions CI build with Ruby 3.1 on Windows that I set up has completed without any problems.
I'm not sure what might be causing your problem. The erorr message you got ("ERROR: Unsupported Ruby platform!") would only appear if the match `RUBY_PLATFORM =~ /mingw/` fails which should not be the case as your Ruby version seems to have a `RUBY_PLATFORM` constant with a matching value.

**Comment by mcorino** [comment] 2024-09-17 16:47
To be complete I now also installed the exact same RubyInstaller release you indicated above on my own Windows 10 machine and ran `gem install wxruby3` (without any problems) and next `wxruby setup` (also without any problems).
Something is off on your system but I can't for the life of me imagine what that may be.

**Comment by mcorino** [comment] 2024-09-19 06:24
Closing since there do not seem to be any new facts forthcoming.

**Closed by mcorino** 2024-09-19 06:24 UTC
