### ISSUE TITLE
Can't build/install, Unsupported Ruby platform!

### ISSUE THREAD

**Issue by Raxelgrande** [mcorino/wxRuby3#305] opened 2024-09-29 05:59 UTC
### Description
Doing the gem installation gives "Unsupported Ruby platform!" error

```
ERROR:  Error installing wxruby3:
        ERROR: Failed to build gem native extension.
current directory: /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/wxruby3-1.2.0/ext
/home/lucas/.rbenv/versions/3.3.5/bin/ruby mkrf_conf_ext.rb

current directory: /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/wxruby3-1.2.0/ext
/home/lucas/.rbenv/versions/3.3.5/bin/ruby -rrubygems /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.1.0/exe/rake RUBYARCHDIR\=/home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/wxruby3-1.2.0 RUBYLIBDIR\=/home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/wxruby3-1.2.0
(in /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/wxruby3-1.2.0)
ERROR: Unsupported Ruby platform!

rake failed, exit code 1
```

#### To Reproduce:

 you use: wxruby3-1.2.0
- wxRuby3 port  you use: Probably WXGTK
- wxWidgets version  you use: Latest (im not sure)
- OS (distribution)  and its version: Arch Linux latest version 
  + Which GDK  backend is used: Wayland 
  + Desktop environment : KDE

**Comment by mcorino** [comment] 2024-09-29 12:20
I discovered a potential problem with target os detection which may have affected your installation.
This problem has been fixed in the wxRuby3 v1.2.1 version I just released.
Please retry installing using this version.

If this does not succeed supply me with the following additional information.

- your exact commands and output for installing wxRuby3
- the output of running `uname -a`
- the output of running `ruby -e "puts RbConfig::CONFIG['target_os']"`

**Comment by Raxelgrande** [comment] 2024-09-29 14:55
Unfortunately it didn't work. My guess is that retrying "gem install wxruby3" will fetch the latest version available and that it won't use previously downloaded files. 

uname -a Output:` Linux kiryu 6.10.10-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:17:51 +0000 x86_64 GNU/Linux`
ruby command Output: `linux`

Output of installing wxRuby3 (gem install, i can provide the exact steps i use for installing Ruby in my system if needed):
I didn't mention it before but im using the Fish shell instead of the default of Bash. Shouldn't affect things because i already tried to install it with Bash as the shell and it didn't change the result and output.

```
lucas@kiryu ~> gem install wxruby3
Building native extensions. This could take a while...
ERROR:  Error installing wxruby3:
        ERROR: Failed to build gem native extension.

current directory: /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/wxruby3-1.2.1/ext
/home/lucas/.rbenv/versions/3.3.5/bin/ruby mkrf_conf_ext.rb

current directory: /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/wxruby3-1.2.1/ext
/home/lucas/.rbenv/versions/3.3.5/bin/ruby -rrubygems /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rake-13.1.0/exe/rake RUBYARCHDIR\=/home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/wxruby3-1.2.1 RUBYLIBDIR\=/home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/wxruby3-1.2.1
(in /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/wxruby3-1.2.1)
ERROR: Unsupported Ruby platform!

rake failed, exit code 1

Gem files will remain installed in /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/wxruby3-1.2.1 for inspection.
Results logged to /home/lucas/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/wxruby3-1.2.1/gem_make.out
lucas@kiryu ~ [1]>
```

**Comment by mcorino** [comment] 2024-09-30 14:45
Ok, I found the cause of the problem and it's actually not in the wRuby3 gem itself but rather in the `plat4m` gem that is used by the wxRuby3 build scripts to determine the host platform. I obviously did not test this gem sufficiently on ArchLinux :-(.
I have created an update for this gem and was now able to successfully install and build the `wxruby3` gem (be aware there are no prebuilt binaries available for ArchLinux so you will have to run `wxruby setup` after installing the gem; see the docs for details).

The updated `plat4m` gem should be automatically installed when reinstalling the `wxruby3`. Please retry installing wxRuby3 and let me know the result.

**Comment by Raxelgrande** [comment] 2024-09-30 16:46
I tested this and it worked! 
I did have to manually remove and reinstall plat4m. Reinstalling wxruby3 didn't automatically update the dependencies (probably an error in my part). 

After wxruby setup was done i made a file with the hello world button example in the readme, i ran it and it worked perfectly!

**Comment by mcorino** [comment] 2024-10-01 07:21
Thanks for letting me know. I'm glad this is solved.

**Closed by mcorino** 2024-10-01 07:21 UTC
